(function () {
  'use strict';

  const projects = {
    evanssion: { title:'Evanssion', category:'Cybersecurity distribution', image:'evanssion', live:'https://www.evanssion.com/', summary:'Responsive UI development for a cybersecurity company website.', overview:'I developed the approved UI into clear, responsive web pages for desktop, tablet and mobile.', challengeTitle:'Present technical content clearly', challenge:'The website contained many security services and vendor details. The layout needed to stay simple and easy to scan.', goalTitle:'Build a consistent responsive interface', goal:'Keep the design accurate, improve content hierarchy and make navigation easy on every screen size.', flow:['Reviewed the UI design, assets and page structure.','Built the pages with HTML, CSS and jQuery.','Added responsive layouts and simple scroll interactions.','Tested the interface across browsers and devices.'], outcomeTitle:'Clear and consistent UI', outcome:'The finished website presents technical information clearly and works smoothly across desktop, tablet and mobile.' },
    'casa-cacao': { title:'Hotel Casa Cacao', category:'Hospitality', image:'casa-cacao', live:'https://hotelcasacacao.com/en/', summary:'Responsive UI development for a boutique hotel and booking website.', overview:'I built a responsive interface that gives photography, hotel information and booking actions a clear structure.', challengeTitle:'Balance images and booking controls', challenge:'Large photographs and booking tools needed to remain usable without crowding smaller screens.', goalTitle:'Create a smooth booking experience', goal:'Keep the visual style elegant while making rooms, hotel details and booking actions easy to access.', flow:['Reviewed page layouts and image behavior.','Developed flexible content and gallery sections.','Adapted navigation and booking controls for touch screens.','Tested spacing, typography and browser behavior.'], outcomeTitle:'An elegant responsive experience', outcome:'The website keeps its visual character while offering a simple booking journey on every device.' },
    'barcelona-activa': { title:'Barcelona Activa', category:'Government / Public sector', image:'barcelona-activa', live:'https://www.barcelonactiva.cat/', summary:'Accessible UI development for a large public-service portal.', overview:'I developed responsive templates that organize employment, training and business services for different users.', challengeTitle:'Organize a large amount of content', challenge:'The portal had many menus, services and content types that needed to remain clear on small screens.', goalTitle:'Make public services easy to find', goal:'Create accessible layouts, simple navigation and reusable page patterns for all screen sizes.', flow:['Mapped navigation and common page sections.','Built semantic and reusable responsive templates.','Tested menus, cards and content at key breakpoints.','Improved keyboard access and visual consistency.'], outcomeTitle:'A more usable service portal', outcome:'Users can find important services more easily through a clear, responsive and accessible interface.' },
    ecarevault: { title:'eCare Vault', category:'Healthcare technology', image:'ecarevault', live:'https://ecarevault.com/', summary:'Responsive UI development for a healthcare collaboration platform.', overview:'I developed a friendly product website that explains the platform with clear sections and simple user paths.', challengeTitle:'Make a complex platform easy to understand', challenge:'Different healthcare users needed to understand the product without reading dense technical content.', goalTitle:'Create a clear and trustworthy interface', goal:'Use strong hierarchy, approachable visuals and responsive layouts to support product discovery.', flow:['Reviewed user paths and approved UI designs.','Built reusable sections and responsive components.','Improved navigation, calls to action and interaction feedback.','Tested accessibility and layout behavior across devices.'], outcomeTitle:'A simple healthcare product journey', outcome:'The final UI makes the product easier to understand and keeps important actions visible on every screen.' },
    'ibus-global': { title:'iBUS Global', category:'Digital infrastructure', image:'ibus-global', live:'https://ibusglobal.com/', summary:'Responsive UI development for an enterprise connectivity website.', overview:'I translated the visual design into a responsive corporate website with clear service and industry sections.', challengeTitle:'Simplify technical service pages', challenge:'Detailed infrastructure content and large illustrations needed to work together without making pages feel heavy.', goalTitle:'Build a clear enterprise interface', goal:'Make solutions easy to browse while keeping the design consistent and responsive across devices.', flow:['Reviewed content, illustrations and layout rules.','Developed responsive service and industry sections.','Adjusted typography, spacing and interactions by breakpoint.','Completed browser testing and final UI checks.'], outcomeTitle:'A focused responsive website', outcome:'The site presents connectivity services through a clear interface that works consistently on all major devices.' },
    dotsolved: { title:'dotSolved', category:'Enterprise AI', image:'dotsolved', live:'https://dotsolved.com/', summary:'Responsive UI development for an enterprise AI services website.', overview:'I built a modern interface that organizes AI services, platforms and supporting content into clear sections.', challengeTitle:'Keep the AI content focused', challenge:'Several service areas needed to fit into one website without creating a crowded or confusing experience.', goalTitle:'Create a simple path through services', goal:'Use clear hierarchy, reusable UI patterns and responsive behavior to help users explore the content.', flow:['Reviewed the design system and content hierarchy.','Built responsive sections for services and industries.','Added light motion and clear interaction feedback.','Tested layouts and browser compatibility.'], outcomeTitle:'A clean enterprise UI', outcome:'The finished interface makes the AI service offering easier to scan and consistent across screen sizes.' },
    'bnb-security': { title:'BNB Security & Automation', category:'Security / Building automation', image:'bnb-security', live:'https://www.bnbinfosys.com/', summary:'Responsive UI development for a security and building automation company.', overview:'I developed a corporate website that organizes security, safety and automation services into clear page sections.', challengeTitle:'Show many services without clutter', challenge:'The broad service list needed a simple structure that users could understand quickly on any device.', goalTitle:'Build a clear service experience', goal:'Create responsive layouts, consistent navigation and visible enquiry actions throughout the website.', flow:['Grouped content into clear service sections.','Developed responsive pages and navigation.','Refined buttons, spacing and mobile interactions.','Tested key pages, forms and browsers.'], outcomeTitle:'A simple route to each service', outcome:'The final UI helps users understand the service range and reach the enquiry action with less effort.' },
    huco: { title:'Huco', category:'Technology consulting', image:'huco', live:'https://huco.co/', summary:'Responsive UI development for a technology consulting website.', overview:'I created a structured responsive interface for consulting services, company information and technology content.', challengeTitle:'Give broad services a clear structure', challenge:'Multiple service areas needed a consistent layout without long or difficult navigation paths.', goalTitle:'Make the website easy to explore', goal:'Build readable pages, reusable interface patterns and responsive navigation for desktop and mobile users.', flow:['Reviewed content and planned the page hierarchy.','Developed responsive layouts and shared UI styles.','Refined typography, spacing and navigation states.','Tested the website across browsers and screen sizes.'], outcomeTitle:'A consistent consulting interface', outcome:'The website presents its services through a simple structure with reliable responsive behavior.' },
    'ariel-group': { title:'Ariel Group', category:'Leadership development', image:'ariel-group', live:'https://www.arielgroup.com/', summary:'Responsive UI development for a leadership learning website.', overview:'I developed a responsive experience that connects users with training programs, coaching and useful resources.', challengeTitle:'Support different learning journeys', challenge:'Individuals and business teams needed clear ways to find the right program without complex navigation.', goalTitle:'Make programs easy to discover', goal:'Create a simple content hierarchy, responsive layouts and clear interaction states across the website.', flow:['Reviewed program content and approved UI designs.','Built responsive program and resource sections.','Improved navigation and interaction feedback.','Tested important user journeys across devices.'], outcomeTitle:'A clearer learning experience', outcome:'Users can explore programs and reach relevant information through a clean and consistent responsive interface.' }
  };

  const details = {
    evanssion: { overviewTitle:'Responsive security website UI', role:'UI development, responsive layouts, jQuery interactions', delivery:'Corporate website', workflowTitle:'From design to tested interface', labels:['UI review','Front-end build','Responsive testing','Final QA'], highlights:['Clear content hierarchy','Simple navigation','Consistent responsive UI'] },
    'casa-cacao': { overviewTitle:'A visual hotel booking interface', role:'UI development, responsive layouts, booking interactions', delivery:'Hotel website', workflowTitle:'Building the responsive experience', labels:['UI review','Page build','Mobile controls','Final QA'], highlights:['Strong image layouts','Clear booking actions','Touch-friendly interface'] },
    'barcelona-activa': { overviewTitle:'Accessible public-service UI', role:'UI development, responsive templates, accessibility', delivery:'Public-service portal', workflowTitle:'Creating reusable page patterns', labels:['Content review','Template build','Breakpoint tests','Accessibility QA'], highlights:['Accessible navigation','Reusable templates','Responsive service cards'] },
    ecarevault: { overviewTitle:'A clear healthcare product UI', role:'UI development, responsive implementation, interaction design', delivery:'Product website', workflowTitle:'Building a simple product journey', labels:['UI review','Component build','Interaction pass','Device testing'], highlights:['Clear product sections','Visible calls to action','Accessible responsive UI'] },
    'ibus-global': { overviewTitle:'Responsive enterprise website UI', role:'UI development, responsive implementation, browser testing', delivery:'Corporate website', workflowTitle:'Developing the interface', labels:['Layout review','Page build','Responsive tuning','Browser QA'], highlights:['Clear service layouts','Consistent navigation','Flexible visual content'] },
    dotsolved: { overviewTitle:'A modern enterprise AI interface', role:'UI development, responsive implementation, motion effects', delivery:'Marketing website', workflowTitle:'Creating reusable UI patterns', labels:['UI review','Section build','Motion pass','Browser QA'], highlights:['Scannable content','Responsive components','Simple interactions'] },
    'bnb-security': { overviewTitle:'A clear security services UI', role:'UI development, responsive implementation, interaction support', delivery:'Corporate website', workflowTitle:'Building the service pages', labels:['Content review','Page build','Mobile tuning','Journey testing'], highlights:['Organized services','Clear enquiry actions','Responsive navigation'] },
    huco: { overviewTitle:'A structured consulting website', role:'UI development, responsive layouts, cross-browser testing', delivery:'Corporate website', workflowTitle:'Building a consistent interface', labels:['Content review','Layout build','UI refinement','Browser testing'], highlights:['Readable layouts','Simple navigation','Consistent page styles'] },
    'ariel-group': { overviewTitle:'A responsive learning interface', role:'UI development, responsive implementation, content interactions', delivery:'Learning website', workflowTitle:'Building clear program journeys', labels:['UI review','Page build','Interaction pass','Journey testing'], highlights:['Clear program paths','Responsive content','Consistent interactions'] }
  };

  const briefs = {
    evanssion: 'A consistent visual hierarchy guides users through vendors, services and security solutions.',
    'casa-cacao': 'The layout keeps the hotel photography prominent while making booking information easy to find.',
    'barcelona-activa': 'Reusable UI patterns help varied public information feel familiar and accessible across pages.',
    ecarevault: 'Readable content, approachable visuals and clear actions support the healthcare audience.',
    'ibus-global': 'Illustrations and structured content blocks make complex infrastructure services easier to understand.',
    dotsolved: 'Reusable sections and light interactions create a focused experience across service pages.',
    'bnb-security': 'Strong visual grouping helps users understand the complete range of connected services.',
    huco: 'Clear typography and consistent spacing make detailed consulting content easier to scan.',
    'ariel-group': 'Simple content paths support both individual learners and business teams.'
  };

  const order = Object.keys(projects);
  const key = new URLSearchParams(window.location.search).get('project') || order[0];
  const project = projects[key] || projects[order[0]];
  const detail = details[key] || details[order[0]];
  const set = (selector, value) => { const el = document.querySelector(selector); if (el) el.textContent = value; };

  set('[data-title]', project.title); set('[data-category]', project.category); set('[data-summary]', project.summary);
  set('[data-role]', detail.role); set('[data-delivery]', detail.delivery); set('[data-overview-title]', detail.overviewTitle);
  set('[data-overview]', project.overview + ' ' + briefs[key]); set('[data-challenge-title]', project.challengeTitle); set('[data-challenge]', project.challenge);
  set('[data-goal-title]', project.goalTitle); set('[data-goal]', project.goal); set('[data-workflow-title]', detail.workflowTitle);
  set('[data-outcome-title]', project.outcomeTitle); set('[data-outcome]', project.outcome);
  project.flow.forEach((text, index) => set('[data-flow-' + (index + 1) + ']', text));
  detail.labels.forEach((text, index) => set('[data-flow-label-' + (index + 1) + ']', text));
  detail.highlights.forEach((text, index) => set('[data-highlight-' + (index + 1) + ']', text));

  const image = document.querySelector('[data-image]');
  image.src = '../assets/projects/' + project.image + '/responsive-mockup.png';
  image.alt = project.title + ' website shown on desktop, tablet and mobile';

  const live = document.querySelector('[data-live]');
  if (project.live) live.href = project.live; else live.hidden = true;
  document.title = project.title + ' Case Study | Rajasekar G.';

  const index = order.indexOf(key);
  const prev = order[(index - 1 + order.length) % order.length];
  const next = order[(index + 1) % order.length];
  const prevLink = document.querySelector('[data-prev]');
  const nextLink = document.querySelector('[data-next]');
  prevLink.href = '?project=' + prev; nextLink.href = '?project=' + next;
  prevLink.querySelector('span').textContent = projects[prev].title;
  nextLink.querySelector('span').textContent = projects[next].title;
})();
